WARNING:tensorflow:From /home/ubuntu/venv-tf2.2.0/lib/python3.6/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-06-19 00:14:15.730517: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-06-19 00:14:15.757884: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2100000000 Hz
2020-06-19 00:14:15.758218: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f86c0000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-19 00:14:15.758265: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-19 00:14:15.763780: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-19 00:14:16.013782: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x50c8670 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-06-19 00:14:16.013841: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Quadro RTX 8000, Compute Capability 7.5
2020-06-19 00:14:16.021197: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:1a:00.0 name: Quadro RTX 8000 computeCapability: 7.5
coreClock: 1.77GHz coreCount: 72 deviceMemorySize: 47.46GiB deviceMemoryBandwidth: 625.94GiB/s
2020-06-19 00:14:16.021468: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-19 00:14:16.023796: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-19 00:14:16.025674: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-06-19 00:14:16.026023: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-06-19 00:14:16.028038: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-06-19 00:14:16.029674: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-06-19 00:14:16.034515: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-19 00:14:16.040866: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-19 00:14:16.040893: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-19 00:14:16.043566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-19 00:14:16.043576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2020-06-19 00:14:16.043579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2020-06-19 00:14:16.048153: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 45523 MB memory) -> physical GPU (device: 0, name: Quadro RTX 8000, pci bus id: 0000:1a:00.0, compute capability: 7.5)
Traceback (most recent call last):
File "tf_cnn_benchmarks.py", line 73, in <module>
app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
File "/home/ubuntu/venv-tf2.2.0/lib/python3.6/site-packages/absl/app.py", line 299, in run
_run_main(main, args)
File "/home/ubuntu/venv-tf2.2.0/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
sys.exit(main(argv))
File "tf_cnn_benchmarks.py", line 62, in main
bench = benchmark_cnn.BenchmarkCNN(params)
File "/home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1305, in __init__
self.params.model, self.dataset, self.params)
File "/home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/models/model_config.py", line 134, in get_model_config
model = model_map[model_name](params=params)
TypeError: 'str' object is not callable
